### ISSUE TITLE
Can't get pads and knobs to respond

### ISSUE THREAD

**Issue by AnAvidEditor** [johnbotris/mpk-mini-mkii-bitwig-script#1]
Hi! I installed the script and loaded the program. I can play the keys and get a response from Bitwig but no matter what I try I cant seem to get the pads or knobs working. Is there something I may be missing? Thanks!

**Comment by johnbotris** [comment]
Which version of Bitwig are you using? and have you installed the program onto your MPK using the editor?

**Comment by AnAvidEditor** [comment]
I’m on Bitwig 3.2.4 and yes I installed from the editor and asked it to pull the program from the MPK to the computer as well to make sure it was actually on there.

________________________________

**Comment by johnbotris** [comment]
So for example when you set the pads to CC mode and press them nothing in the UI changes, correct? If you open up the controller script console from the studio IO panel, what kind of output do you get? Is there a section called MPKmini mkII?

**Comment by AnAvidEditor** [comment]
Yes it shows it’s reading it but nothing changes. In my settings I only had the option of MPKmini not the mkII should there be an mkII setting there? When I open up the controller script I think it just said input() I can double check

________________________________

**Comment by johnbotris** [comment]
What do you mean by it shows it's reading?

If you've put the project in the controller scripts directory then in the controller settings you should be able to choose the script MPKmini mkII under Akai.

**Comment by AnAvidEditor** [comment]
It shows input if I push the pad but nothing happens. Under Akai I have

Advanced 25/49/61
APC40 mkII
EWI USB
MPK25
MPK49
MPKmini

Is there a certain structure it should be in in the controller scripts folder

________________________________

**Comment by johnbotris** [comment]
Where/how does it show input? on the MPK or in Bitwig? Try taking the `controller-scripts` folder from the project and putting it directly into the main folder for controller scripts - I have the entire project directly inside `Bitwig Studio/Controller Scripts` though, so I would be surprised if that was the reason

**Comment by AnAvidEditor** [comment]
Omg I found what the problem was. For some reason bitwig created two controller scripts folders. One in my documents and one where it was installed. When I moved it to the one where it was installed it worked. I had it in the documents controller scripts folder. Thanks for helping me out.

________________________________
